version: '3.8'

services:
  evilginx:
    build: 
      context: ./docker/evilginx/
      dockerfile: Dockerfile
    container_name: evilginx_server
    restart: always
    tty: true
    stdin_open: true
    network_mode: "host"
    volumes:
      - evilginx_data:/root/.evilginx
      - /opt/evilginx/phishlets:/app/phishlets

volumes:
  evilginx_data:
    name: evilginx_persistent_data
