---
- name: Konfiguracja bazowa VPS i przygotowanie Firewalla
  hosts: evilginx_server
  become: yes

  tasks:
    - name: Aktualizacja list pakietów (apt update)
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Instalacja niezbędnych narzędzi
      apt:
        name:
          - ipset
          - iptables-persistent
          - curl
        state: present

    - name: Utworzenie folderu firewall_scripts w katalogu domowym
      file:
        path: "{{ ansible_env.HOME }}/firewall_scripts"
        state: directory
        mode: '0755'

    - name: Wgranie Twojego skryptu update_pl_ips.sh
      copy:
        src: files/update_pl_ips.sh
        dest: "{{ ansible_env.HOME }}/firewall_scripts/update_pl_ips.sh"
        mode: '0755'

    - name: Wgranie skryptu open_ports.sh (otwieranie 80 i 443)
      copy:
        src: files/open_ports.sh
        dest: "{{ ansible_env.HOME }}/firewall_scripts/open_ports.sh"
        mode: '0755'

    - name: Wgranie skryptu close_ports.sh (zamykanie 80 i 443)
      copy:
        src: files/close_ports.sh
        dest: "{{ ansible_env.HOME }}/firewall_scripts/close_ports.sh"
        mode: '0755'

    - name: Pierwsze uruchomienie aktualizacji bazy GeoIP
      command: "{{ ansible_env.HOME }}/firewall_scripts/update_pl_ips.sh"
      register: ipset_result
      changed_when: "'GOTOWE' in ipset_result.stdout"

    - name: Iptables - Pozwól na ruch z pętli zwrotnej (localhost)
      iptables:
        chain: INPUT
        in_interface: lo
        jump: ACCEPT

    - name: Iptables - Pozwól na połącznia już nawiązane (nie zrywaj obecnych)
      iptables:
        chain: INPUT
        ctstate: ESTABLISHED,RELATED
        jump: ACCEPT

    - name: Iptables - Pozwól na dostęp do SSH (port 22)
      iptables:
        chain: INPUT
        protocol: tcp
        destination_port: '22'
        jump: ACCEPT

    - name: Iptables - Pozwól na ruch z Polski (korzysta ze zbioru ipset)
      iptables:
        chain: INPUT
        match: set
        match_set: poland_ips
        match_set_flags: src
        jump: ACCEPT

    - name: Iptables - Zablokuj całą resztę (domyślna polityka DROP)
      iptables:
        chain: INPUT
        policy: DROP

    - name: Zapisz reguły firewalla na stałe (iptables-persistent)
      command: netfilter-persistent save

    - name: Zwolnienie portu 53 (system resolved) - zamiana DNSStubListener
      lineinfile:
        path: /etc/systemd/resolved.conf
        regexp: '^#?DNSStubListener='
        line: 'DNSStubListener=no'

    - name: Zwolnienie portu 53 - naprawa symlinku dla resolv.conf
      file:
        src: /run/systemd/resolve/resolv.conf
        dest: /etc/resolv.conf
        state: link
        force: yes
      notify: Restart systemd-resolved

  handlers:
    - name: Restart systemd-resolved
      systemd:
        name: systemd-resolved
        state: restarted
