---
- name: Deploy Evilginx
  hosts: evilginx_server
  become: yes

  vars:
    install_path: "/usr/share/evilginx"
    scripts_path: "{{ ansible_env.HOME }}/firewall_scripts"
    go_version: "1.23.0"

  tasks:
    - name: Install system requirements
      apt:
        name: [git, make, gcc, wget, tar, ipset, iptables-persistent, curl]
        state: present
        update_cache: yes

    - name: Disable systemd-resolved to free port 53
      systemd:
        name: systemd-resolved
        state: stopped
        enabled: no

    - name: Set static nameserver (DNS fix)
      copy:
        dest: /etc/resolv.conf
        content: "nameserver 1.1.1.1"

    - name: Install Golang
      shell: |
        wget -q https://go.dev/dl/go{{ go_version }}.linux-amd64.tar.gz
        rm -rf /usr/local/go && tar -C /usr/local -xzf go{{ go_version }}.linux-amd64.tar.gz
      args:
        creates: /usr/local/go

    - name: Create directories
      file:
        path: "{{ item }}"
        state: directory
      loop:
        - "{{ install_path }}"
        - "{{ install_path }}/phishlets"
        - "{{ scripts_path }}"

    - name: Clone Evilginx repository
      git:
        repo: https://github.com/kgretzky/evilginx2.git
        dest: "{{ install_path }}/src"
        force: yes

    - name: Build Evilginx
      shell:
        cmd: |
          export PATH=$PATH:/usr/local/go/bin
          make
        chdir: "{{ install_path }}/src"
        creates: "{{ install_path }}/src/build/evilginx"

    - name: Create symlink for evilginx command
      file:
        src: "{{ install_path }}/src/build/evilginx"
        dest: /usr/local/bin/evilginx
        state: link

    - name: Copy example phishlet
      command: "cp {{ install_path }}/src/phishlets/example.yaml {{ install_path }}/phishlets/"
      args:
        creates: "{{ install_path }}/phishlets/example.yaml"

    - name: Copy firewall scripts
      copy:
        src: files/
        dest: "{{ scripts_path }}/"
        mode: '0755'

    - name: Initialize GeoIP database
      command: "{{ scripts_path }}/update_ips.sh"
      changed_when: true

    - name: Setup Systemd Service
      copy:
        dest: /etc/systemd/system/evilginx.service
        content: |
          [Unit]
          Description=Evilginx Service
          After=network.target

          [Service]
          Type=simple
          WorkingDirectory={{ install_path }}
          ExecStart=/usr/local/bin/evilginx -p {{ install_path }}/phishlets
          Restart=always

          [Install]
          WantedBy=multi-user.target
